(ns phzr.impl.accessors.utils.debug)

(def debug-get-properties
  {:bmd "bmd"
   :canvas "canvas"
   :column-width "columnWidth"
   :context "context"
   :current-alpha "currentAlpha"
   :current-x "currentX"
   :current-y "currentY"
   :dirty "dirty"
   :font "font"
   :game "game"
   :line-height "lineHeight"
   :render-shadow "renderShadow"
   :sprite "sprite"})

(def debug-set-properties
  {:bmd "bmd"
   :canvas "canvas"
   :column-width "columnWidth"
   :context "context"
   :current-alpha "currentAlpha"
   :current-x "currentX"
   :current-y "currentY"
   :dirty "dirty"
   :font "font"
   :game "game"
   :line-height "lineHeight"
   :render-shadow "renderShadow"
   :sprite "sprite"})