(ns phzr.impl.accessors.time)

(def time-get-properties
  {:advanced-timing "advancedTiming"
   :desired-fps "desiredFps"
   :events "events"
   :fps "fps"
   :fps-max "fpsMax"
   :fps-min "fpsMin"
   :frames "frames"
   :ms-max "msMax"
   :ms-min "msMin"
   :pause-duration "pauseDuration"
   :physics-elapsed "physicsElapsed"
   :physics-elapsed-ms "physicsElapsedMS"
   :slow-motion "slowMotion"
   :suggested-fps "suggestedFps"})

(def time-set-properties
  {:advanced-timing "advancedTiming"
   :desired-fps "desiredFps"
   :events "events"
   :fps-max "fpsMax"
   :fps-min "fpsMin"
   :ms-max "msMax"
   :ms-min "msMin"
   :pause-duration "pauseDuration"
   :physics-elapsed "physicsElapsed"
   :physics-elapsed-ms "physicsElapsedMS"
   :slow-motion "slowMotion"
   :suggested-fps "suggestedFps"})