(ns phzr.impl.accessors.pixi.canvas-renderer)

(def canvas-renderer-get-properties
  {:transparent "transparent"
   :refresh "refresh"
   :clear-before-render "clearBeforeRender"
   :width "width"
   :type "type"
   :auto-resize "autoResize"
   :canvas-mask-manager "CanvasMaskManager"
   :resolution "resolution"
   :count "count"
   :render-session "renderSession"
   :context "context"
   :view "view"
   :height "height"})

(def canvas-renderer-set-properties
  {:transparent "transparent"
   :refresh "refresh"
   :clear-before-render "clearBeforeRender"
   :width "width"
   :type "type"
   :auto-resize "autoResize"
   :canvas-mask-manager "CanvasMaskManager"
   :resolution "resolution"
   :count "count"
   :render-session "renderSession"
   :context "context"
   :view "view"
   :height "height"})