(ns phzr.impl.accessors.pixi.webgl-fast-sprite-batch)

(def webgl-fast-sprite-batch-get-properties
  {:vertices "vertices"
   :current-base-texture "currentBaseTexture"
   :current-blend-mode "currentBlendMode"
   :last-index-count "lastIndexCount"
   :max-size "maxSize"
   :vert-size "vertSize"
   :size "size"
   :vertex-buffer "vertexBuffer"
   :matrix "matrix"
   :current-batch-size "currentBatchSize"
   :render-session "renderSession"
   :drawing "drawing"
   :indices "indices"
   :index-buffer "indexBuffer"
   :shader "shader"})

(def webgl-fast-sprite-batch-set-properties
  {:vertices "vertices"
   :current-base-texture "currentBaseTexture"
   :current-blend-mode "currentBlendMode"
   :last-index-count "lastIndexCount"
   :max-size "maxSize"
   :vert-size "vertSize"
   :size "size"
   :vertex-buffer "vertexBuffer"
   :matrix "matrix"
   :current-batch-size "currentBatchSize"
   :render-session "renderSession"
   :drawing "drawing"
   :indices "indices"
   :index-buffer "indexBuffer"
   :shader "shader"})